### PR TITLE
README: Add follow-up refinements

### PR DESCRIPTION
**Pull request by luzpaz**
* Add mention of Blender  
* Add missing URLs  
* Hide optional deps in collapsed div in order to declutter  
* Other tweaks

Preview: https://github.com/luzpaz/TopologicSverchok/blob/README/README.md

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: it would be helpful to specify the minimum version required for hard dependencies in Prerequistes (https://github.com/luzpaz/TopologicSverchok/blob/README/README.md#prerequisites) and optional ones https://github.com/luzpaz/TopologicSverchok/blob/README/README.md#optional-dependencies

**Comment by wassimj** [comment]
Please sign LCA for this to proceed

**Comment by luzpaz** [comment]
I have
Screenshot_20220829_082748

**Comment by luzpaz** [comment]
Maybe you have 2 accounts or recently modified your username somehow ?

**Pull request merged**
